using StaticArrays
using Base.Test

# We generate a lot of matrices using rand(), but unit tests should be
# deterministic, so seed the RNG here.
srand(42)

include("testutil.jl")
include("SVector.jl")
include("MVector.jl")
include("SMatrix.jl")
include("MMatrix.jl")
include("SArray.jl")
include("MArray.jl")
include("FieldVector.jl")
include("Scalar.jl")
include("SUnitRange.jl")
include("SizedArray.jl")
include("SDiagonal.jl")

include("custom_types.jl")
include("core.jl")
include("abstractarray.jl")
include("indexing.jl")
include("mapreduce.jl")
include("arraymath.jl")
include("broadcast.jl")
include("linalg.jl")
include("matrix_multiply.jl")
include("triangular.jl")
include("det.jl")
include("inv.jl")
include("solve.jl")
include("eigen.jl")
include("expm.jl")
include("sqrtm.jl")
include("lyap.jl")
include("lu.jl")
include("qr.jl")
include("chol.jl")
include("deque.jl")
include("io.jl")
include("svd.jl")
include("fixed_size_arrays.jl")
